version: "3.5"

services:
  user_api:
    container_name: user_api
    build:
      context: .
      dockerfile: Dockerfile
    image: user_api:0.1.0
    environment: 
      - SECRET_KEY
    volumes:
      - .:/app
    working_dir: /app
    command: >
        bash -cx "cd user_api/docs; make clean; make html; cd .. &&
        gunicorn --workers=3 --worker-class=uvicorn.workers.UvicornWorker --timeout=174000 --bind=0.0.0.0:4090 'app:start_application()'"
    ports:
      - 4090:4090
    networks:
      - user-network
    depends_on:
      - db_user
  
  db_user:
    container_name: db_user
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB=userapi
      - POSTGRES_PASSWORD=userapi
      - POSTGRES_USER=userapi
    ports:
      - 15432:5432
    volumes:
      - vdb_user:/var/lib/postgresql/data/
    networks:
      - user-network

  pgadmin_userapi:
    container_name: pgadmin_userapi
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=userapi@email.com
      - PGADMIN_DEFAULT_PASSWORD=userapi
    ports:
      - 8032:80
    depends_on:
      - db_user
    networks:
      - user-network

networks:
  user-network:
    name: user-network
    driver: bridge

volumes:
    vdb_user:
